/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(auth)/login': RouteRecordInfo<'/(auth)/login', '/login', Record<never, never>, Record<never, never>>,
    '/(manage)/[...all]': RouteRecordInfo<'/(manage)/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/(manage)/admin': RouteRecordInfo<'/(manage)/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/': RouteRecordInfo<'/(manage)/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/district/': RouteRecordInfo<'/(manage)/admin/district/', '/admin/district', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/favorite/': RouteRecordInfo<'/(manage)/admin/favorite/', '/admin/favorite', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/host/': RouteRecordInfo<'/(manage)/admin/host/', '/admin/host', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/hotel/': RouteRecordInfo<'/(manage)/admin/hotel/', '/admin/hotel', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/merchant/': RouteRecordInfo<'/(manage)/admin/merchant/', '/admin/merchant', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/merchant/[id]/': RouteRecordInfo<'/(manage)/admin/merchant/[id]/', '/admin/merchant/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(manage)/admin/message/': RouteRecordInfo<'/(manage)/admin/message/', '/admin/message', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/order/': RouteRecordInfo<'/(manage)/admin/order/', '/admin/order', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/priceRange/': RouteRecordInfo<'/(manage)/admin/priceRange/', '/admin/priceRange', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/product/': RouteRecordInfo<'/(manage)/admin/product/', '/admin/product', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/user/': RouteRecordInfo<'/(manage)/admin/user/', '/admin/user', Record<never, never>, Record<never, never>>,
    '/(manage)/admin/user/[id]/': RouteRecordInfo<'/(manage)/admin/user/[id]/', '/admin/user/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(user)/': RouteRecordInfo<'/(user)/', '/', Record<never, never>, Record<never, never>>,
    '/(user)//': RouteRecordInfo<'/(user)//', '/', Record<never, never>, Record<never, never>>,
    '/(user)//favorite/': RouteRecordInfo<'/(user)//favorite/', '/favorite', Record<never, never>, Record<never, never>>,
    '/(user)//hotel/': RouteRecordInfo<'/(user)//hotel/', '/hotel', Record<never, never>, Record<never, never>>,
    '/(user)//hotel/[id]/': RouteRecordInfo<'/(user)//hotel/[id]/', '/hotel/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(user)//merchant/': RouteRecordInfo<'/(user)//merchant/', '/merchant', Record<never, never>, Record<never, never>>,
    '/(user)//merchant/[id]/': RouteRecordInfo<'/(user)//merchant/[id]/', '/merchant/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(user)//order/': RouteRecordInfo<'/(user)//order/', '/order', Record<never, never>, Record<never, never>>,
    '/(user)//order/[id]/': RouteRecordInfo<'/(user)//order/[id]/', '/order/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(user)//photoGraphy/': RouteRecordInfo<'/(user)//photoGraphy/', '/photoGraphy', Record<never, never>, Record<never, never>>,
    '/(user)//photoGraphy/[id]/': RouteRecordInfo<'/(user)//photoGraphy/[id]/', '/photoGraphy/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(user)//profile/': RouteRecordInfo<'/(user)//profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/(user)//siyi/': RouteRecordInfo<'/(user)//siyi/', '/siyi', Record<never, never>, Record<never, never>>,
    '/(user)//siyi/[id]/': RouteRecordInfo<'/(user)//siyi/[id]/', '/siyi/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(user)/[...all]': RouteRecordInfo<'/(user)/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/(common)/upload/': RouteRecordInfo<'/(common)/upload/', '/upload', Record<never, never>, Record<never, never>>,
  }
}
