/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(admin)/[...admin_all]': RouteRecordInfo<'/(admin)/[...admin_all]', '/:admin_all(.*)', { admin_all: ParamValue<true> }, { admin_all: ParamValue<false> }>,
    '/(admin)/admin': RouteRecordInfo<'/(admin)/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/': RouteRecordInfo<'/(admin)/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/district/': RouteRecordInfo<'/(admin)/admin/district/', '/admin/district', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/hotel/': RouteRecordInfo<'/(admin)/admin/hotel/', '/admin/hotel', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/merchant/': RouteRecordInfo<'/(admin)/admin/merchant/', '/admin/merchant', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/merchant/[id]/': RouteRecordInfo<'/(admin)/admin/merchant/[id]/', '/admin/merchant/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(admin)/admin/photography/': RouteRecordInfo<'/(admin)/admin/photography/', '/admin/photography', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/priceRange/': RouteRecordInfo<'/(admin)/admin/priceRange/', '/admin/priceRange', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/siyi/': RouteRecordInfo<'/(admin)/admin/siyi/', '/admin/siyi', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/user/': RouteRecordInfo<'/(admin)/admin/user/', '/admin/user', Record<never, never>, Record<never, never>>,
    '/(admin)/admin/user/[id]/': RouteRecordInfo<'/(admin)/admin/user/[id]/', '/admin/user/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(auth)/login': RouteRecordInfo<'/(auth)/login', '/login', Record<never, never>, Record<never, never>>,
    '/(user)/': RouteRecordInfo<'/(user)/', '/', Record<never, never>, Record<never, never>>,
    '/(user)//': RouteRecordInfo<'/(user)//', '/', Record<never, never>, Record<never, never>>,
    '/(user)//activity/': RouteRecordInfo<'/(user)//activity/', '/activity', Record<never, never>, Record<never, never>>,
    '/(user)//activity/[id]/': RouteRecordInfo<'/(user)//activity/[id]/', '/activity/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(user)//hotel/': RouteRecordInfo<'/(user)//hotel/', '/hotel', Record<never, never>, Record<never, never>>,
    '/(user)//hotel/[id]/': RouteRecordInfo<'/(user)//hotel/[id]/', '/hotel/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(user)//photoGraphy/': RouteRecordInfo<'/(user)//photoGraphy/', '/photoGraphy', Record<never, never>, Record<never, never>>,
    '/(user)//photoGraphy/[id]/': RouteRecordInfo<'/(user)//photoGraphy/[id]/', '/photoGraphy/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(user)//profile/': RouteRecordInfo<'/(user)//profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/(user)//siyi/': RouteRecordInfo<'/(user)//siyi/', '/siyi', Record<never, never>, Record<never, never>>,
    '/(user)/[...all]': RouteRecordInfo<'/(user)/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
  }
}
