import { ref } from 'vue'

// Hotel data
export const hotels = ref([
  {
    id: 1,
    name: '梦幻婚纱摄影工作室 1',
    image: '/images/hotels/hotel1.jpg',
    featuredImage: '/images/hotels/featured1.jpg',
    rating: 3,
    location: '深圳',
    branch: '预约免费车接送店',
    price: '¥15000以上',
    priceValue: 15000,
    district: 'futian',
    recommended: true,
  },
  {
    id: 2,
    name: '梦幻婚纱摄影工作室 2',
    image: '/images/hotels/hotel2.jpg',
    featuredImage: '/images/hotels/featured2.jpg',
    rating: 3,
    location: '北京',
    branch: '预约免费车接送店',
    price: '¥15000以上',
    priceValue: 15000,
    district: 'chaoyang',
    recommended: true,
  },
  {
    id: 3,
    name: '梦幻婚纱摄影工作室 3',
    image: '/images/hotels/hotel3.jpg',
    featuredImage: '/images/hotels/featured3.jpg',
    rating: 3,
    location: '广州',
    branch: '预约免费车接送店',
    price: '¥3000-8000',
    priceValue: 5000,
    district: 'haizhu',
    recommended: true,
  },
  {
    id: 4,
    name: '水晶之恋婚纱摄影',
    image: '/images/hotels/hotel4.jpg',
    featuredImage: '/images/hotels/featured4.jpg',
    rating: 4,
    location: '北京',
    branch: '朝阳店',
    price: '¥6999起',
    priceValue: 6999,
    district: 'chaoyang',
    recommended: false,
  },
  {
    id: 5,
    name: '韩国匠艺婚纱摄影',
    image: '/images/hotels/hotel5.jpg',
    featuredImage: '/images/hotels/featured5.jpg',
    rating: 5,
    location: '北京',
    branch: '西城区店',
    price: '¥8888起',
    priceValue: 8888,
    district: 'xicheng',
    recommended: false,
  },
])
